"""
p4b_statistical_tests.py
=========================
Formal statistical tests for PopQA ablation study.

  TEST 1 — McNemar Test (paired comparison between configurations):
    Compares two systems on the SAME queries. Requires only ~30 
    discordant queries to achieve sufficient statistical power (p<0.05).
    Standard in NLP for classifier comparison on identical test sets
    (Dror et al., 2018, "Hitchhiker's Guide to Testing Statistical
    Significance in NLP", ACL 2018).

    Statistic: χ²=(b-c)²/(b+c) with b=disagree(A=1,B=0), c=disagree(A=0,B=1)
    Distribution: χ²(df=1) under H₀ (both systems have same error rate)
    Correction: Edwards continuity correction (b+c≥25) or exact (b+c<25)

  TEST 2 — Bootstrap Confidence Intervals (95% CI on EM/F1):
    Resampling with replacement: 10,000 bootstrap samples.
    95% CI = percentiles [2.5, 97.5] of the bootstrap distribution.
    More reliable than normal approximation for small samples.
    Reference: Efron & Hastie (2016), Computer Age Statistical Inference.

  TEST 3 — Wilcoxon Signed-Rank Test (non‑parametric alternative):
    Compares EM distributions per s_pop bucket between configurations.
    Does not assume normality — appropriate for binary EM {0,1}.

OUTPUT:
  results/statistical_tests/mcnemar_results.csv
  results/statistical_tests/bootstrap_ci.csv
  results/statistical_tests/statistical_report.txt
  results/statistical_tests/fig_em_distributions.png
"""

import os
import sys
import csv
import math
import warnings
import numpy as np
from collections import defaultdict
from typing import Dict, List, Optional, Tuple
from scipy import stats as sp_stats

warnings.filterwarnings("ignore")

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    MATPLOTLIB_AVAILABLE = True
except ImportError:
    MATPLOTLIB_AVAILABLE = False

BASE_DIR   = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STAT_DIR   = os.path.join(BASE_DIR, "results", "statistical_tests")
os.makedirs(STAT_DIR, exist_ok=True)

# Point directly to the CSV file generated by p3
CSV_INPUT = os.path.join(BASE_DIR, "results_popqa_v13.csv")

N_BOOTSTRAP  = 10_000
ALPHA        = 0.05
RANDOM_SEED  = 42
BUCKET_ORDER = ["high", "medium", "low"]


# ═════════════════════════════════════════════════════════════════════════════
# SECTION 1: DATA LOADING
# ═════════════════════════════════════════════════════════════════════════════

def safe_float(v: str) -> Optional[float]:
    try:
        f = float(v)
        return f if math.isfinite(f) else None
    except (ValueError, TypeError):
        return None


def load_results(csv_path: str) -> Dict[str, Dict[str, Dict]]:
    """
    Load results from CSV and organise them as:
    {combination: {query_id: {em, f1, s_pop, pop_bucket, route}}}
    """
    print(f"[LOAD] {csv_path}")
    results: Dict[str, Dict[str, Dict]] = defaultdict(dict)

    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            pre   = row.get("pre_strategy","")
            post  = row.get("post_strategy","")
            qid   = row.get("query_id","")
            combo = f"{pre} × {post}"

            em  = safe_float(row.get("em",""))
            f1  = safe_float(row.get("f1",""))
            if em is None or not qid: continue

            results[combo][qid] = {
                "em":         em,
                "f1":         f1 or 0.0,
                "s_pop":      safe_float(row.get("s_pop","1")) or 1.0,
                "pop_bucket": row.get("pop_bucket","unknown"),
                "route":      row.get("route_taken",""),
            }

    n_combos = len(results)
    n_q      = max(len(v) for v in results.values()) if results else 0
    print(f"[LOAD] {n_combos} combinations, max {n_q} queries per combination.")
    return dict(results)


def get_shared_queries(results: Dict[str, Dict[str, Dict]],
                       combo_a: str, combo_b: str) -> List[str]:
    """Return query IDs present in BOTH combinations."""
    set_a = set(results.get(combo_a, {}).keys())
    set_b = set(results.get(combo_b, {}).keys())
    return sorted(set_a & set_b)


# ═════════════════════════════════════════════════════════════════════════════
# SECTION 2: TEST 1 — McNemar
# ═════════════════════════════════════════════════════════════════════════════

def mcnemar_test(em_a: List[float], em_b: List[float]) -> Dict:
    """
    McNemar test for paired comparison of binary classifiers.
    """
    assert len(em_a) == len(em_b), "Both lists must have the same length"

    a = b = c = d = 0
    for ea, eb in zip(em_a, em_b):
        ia, ib = int(round(ea)), int(round(eb))
        if   ia==1 and ib==1: a += 1
        elif ia==1 and ib==0: b += 1
        elif ia==0 and ib==1: c += 1
        else:                  d += 1

    n_disc = b + c

    if n_disc == 0:
        return {
            "statistic": 0.0, "pvalue": 1.0, "b": b, "c": c,
            "n_discordant": 0, "n_total": len(em_a),
            "interpretation": "Identical (no discordant queries)",
            "method": "none",
        }

    if n_disc < 25:
        # Exact binomial test: H₀: P(B=1|discordant) = 0.5
        pvalue = 2 * sp_stats.binom.sf(max(b,c)-1, n_disc, 0.5)
        pvalue = min(pvalue, 1.0)
        statistic = float(b) / n_disc   # Proportion (not χ²)
        method = "exact_binomial"
    else:
        # χ² with Edwards continuity correction
        statistic = (abs(b-c) - 1)**2 / n_disc
        pvalue    = sp_stats.chi2.sf(statistic, df=1)
        method    = "chi2_continuity"

    significant = pvalue < ALPHA
    direction   = "A > B" if b > c else "B > A" if c > b else "="

    return {
        "statistic":     round(float(statistic), 6),
        "pvalue":        round(float(pvalue), 6),
        "b":             b,   # A wins
        "c":             c,   # B wins
        "n_discordant":  n_disc,
        "n_total":       len(em_a),
        "pct_discordant":round(100*n_disc/len(em_a), 1),
        "direction":     direction,
        "significant":   significant,
        "method":        method,
        "interpretation":f"{'SIGNIFICANT' if significant else 'non sig.'} "
                         f"(p={pvalue:.4f}, α={ALPHA}, {direction})",
    }


def run_all_mcnemar(results: Dict[str, Dict[str, Dict]],
                    baseline: str) -> List[Dict]:
    """Run McNemar of every configuration against the baseline."""
    combos = sorted(results.keys())
    rows   = []

    print(f"\n[MCNEMAR] Baseline: '{baseline}'")
    print(f"          {len(combos)-1} comparisons to run\n")

    for combo in combos:
        if combo == baseline: continue

        shared = get_shared_queries(results, baseline, combo)
        if len(shared) < 10:
            print(f"  SKIP {combo}: only {len(shared)} shared queries")
            continue

        em_base  = [results[baseline][q]["em"] for q in shared]
        em_combo = [results[combo][q]["em"]     for q in shared]

        test     = mcnemar_test(em_base, em_combo)
        em_a_mu  = round(np.mean(em_base),  4)
        em_b_mu  = round(np.mean(em_combo), 4)

        row = {
            "system_a":      baseline,
            "system_b":      combo,
            "n_shared":      len(shared),
            "em_a":          em_a_mu,
            "em_b":          em_b_mu,
            "delta_em":      round(em_b_mu - em_a_mu, 4),
            **test,
        }
        rows.append(row)

        sig_marker = "★" if test["significant"] else "○"
        print(f"  {sig_marker} {combo[:42]:<42} | "
              f"ΔEM={em_b_mu-em_a_mu:+.4f} | "
              f"p={test['pvalue']:.4f} | disc={test['n_discordant']} | "
              f"{test['direction']}")

    return rows


# ═════════════════════════════════════════════════════════════════════════════
# SECTION 3: TEST 2 — Bootstrap CI
# ═════════════════════════════════════════════════════════════════════════════

def bootstrap_ci(values: List[float],
                 n_bootstrap: int = N_BOOTSTRAP,
                 alpha: float = ALPHA,
                 seed: int = RANDOM_SEED) -> Tuple[float, float, float]:
    """Bootstrap confidence interval for the mean of a distribution."""
    rng = np.random.RandomState(seed)
    arr = np.array(values, dtype=np.float64)
    n   = len(arr)

    boot_means = np.array([
        np.mean(rng.choice(arr, size=n, replace=True))
        for _ in range(n_bootstrap)
    ])

    ci_lo = float(np.percentile(boot_means, 100*alpha/2))
    ci_hi = float(np.percentile(boot_means, 100*(1-alpha/2)))
    return float(np.mean(arr)), ci_lo, ci_hi


def run_bootstrap_for_all(results: Dict[str, Dict[str, Dict]]) -> List[Dict]:
    """Bootstrap CI for EM and F1 of each combination, overall and per bucket."""
    print(f"\n[BOOTSTRAP] {N_BOOTSTRAP} resamples per combination...")
    rows = []

    for combo in sorted(results.keys()):
        q_data = list(results[combo].values())
        ems    = [r["em"] for r in q_data]
        f1s    = [r["f1"] for r in q_data]
        n      = len(ems)

        em_mean, em_lo, em_hi = bootstrap_ci(ems)
        f1_mean, f1_lo, f1_hi = bootstrap_ci(f1s)

        row = {
            "combination":   combo,
            "n":             n,
            "em_mean":       round(em_mean, 4),
            "em_ci95_lo":    round(em_lo, 4),
            "em_ci95_hi":    round(em_hi, 4),
            "em_ci95_width": round(em_hi - em_lo, 4),
            "f1_mean":       round(f1_mean, 4),
            "f1_ci95_lo":    round(f1_lo, 4),
            "f1_ci95_hi":    round(f1_hi, 4),
        }

        # Bootstrap per bucket
        for bucket in BUCKET_ORDER:
            b_ems = [r["em"] for r in q_data if r.get("pop_bucket")==bucket]
            if len(b_ems) >= 5:
                bm, bl, bh = bootstrap_ci(b_ems)
                row[f"em_{bucket}"]       = round(bm, 4)
                row[f"em_{bucket}_ci_lo"] = round(bl, 4)
                row[f"em_{bucket}_ci_hi"] = round(bh, 4)
            else:
                row[f"em_{bucket}"] = row[f"em_{bucket}_ci_lo"] = row[f"em_{bucket}_ci_hi"] = None

        rows.append(row)
        print(f"  {combo[:42]:<42}: EM={em_mean:.4f} [{em_lo:.4f},{em_hi:.4f}]  "
              f"F1={f1_mean:.4f} [{f1_lo:.4f},{f1_hi:.4f}]")

    return rows


# ═════════════════════════════════════════════════════════════════════════════
# SECTION 4: TEST 3 — Wilcoxon per bucket
# ═════════════════════════════════════════════════════════════════════════════

def run_wilcoxon_bucket(results: Dict[str, Dict[str, Dict]],
                        combo_a: str, combo_b: str) -> Dict:
    """Wilcoxon Signed-Rank test for paired comparison per s_pop bucket."""
    shared = get_shared_queries(results, combo_a, combo_b)
    bucket_results = {}

    for bucket in BUCKET_ORDER:
        shared_b = [q for q in shared
                    if results[combo_a][q].get("pop_bucket") == bucket]
        if len(shared_b) < 10:
            bucket_results[bucket] = {"pvalue": None, "n": len(shared_b)}
            continue

        em_a = [results[combo_a][q]["em"] for q in shared_b]
        em_b = [results[combo_b][q]["em"] for q in shared_b]
        diff = [a-b for a,b in zip(em_a, em_b)]

        if all(d == 0 for d in diff):
            bucket_results[bucket] = {"pvalue": 1.0, "n": len(shared_b),
                                       "direction": "="}
            continue

        try:
            stat, pval = sp_stats.wilcoxon(diff, alternative="two-sided",
                                            correction=True)
            direction = "A>B" if np.mean(diff)>0 else "B>A"
        except ValueError:
            pval, stat, direction = 1.0, 0.0, "="

        bucket_results[bucket] = {
            "pvalue":    round(float(pval), 6),
            "statistic": round(float(stat), 4),
            "n":         len(shared_b),
            "direction": direction,
            "significant": pval < ALPHA,
        }

    return bucket_results


# ═════════════════════════════════════════════════════════════════════════════
# SECTION 5: PLOTS
# ═════════════════════════════════════════════════════════════════════════════

COLORS = {
    "Always_Retrieve": "#888888", "Entropy": "#2196F3",
    "Entropy_PP": "#9C27B0",      "BM25_Always": "#FF9800",
}


def plot_em_distributions(results: Dict[str, Dict[str, Dict]],
                          bootstrap_rows: List[Dict],
                          output_path: str):
    """Forest plot (dot-whisker) of EM with 95% bootstrap CI per configuration."""
    if not MATPLOTLIB_AVAILABLE: return

    boot_map = {r["combination"]: r for r in bootstrap_rows}
    combos   = sorted(results.keys(), key=lambda x: boot_map.get(x,{}).get("em_mean",0))

    fig, axes = plt.subplots(1, 2, figsize=(14, max(6, len(combos)*0.5+2)))

    # Panel 1: global EM forest plot
    ax = axes[0]
    y  = np.arange(len(combos))

    for i, combo in enumerate(combos):
        b = boot_map.get(combo, {})
        if not b: continue
        em   = b.get("em_mean", 0)
        lo   = b.get("em_ci95_lo", em)
        hi   = b.get("em_ci95_hi", em)
        pre  = combo.split(" × ")[0] if " × " in combo else combo
        color = COLORS.get(pre, "#666666")

        ax.plot([lo, hi], [i, i], color=color, lw=2.5, alpha=0.7)
        ax.scatter([em], [i], color=color, s=60, zorder=3)

    ax.set_yticks(y)
    ax.set_yticklabels([c.replace(" × ","\n×") for c in combos], fontsize=8)
    ax.set_xlabel("Exact Match (EM) — 95% Bootstrap CI", fontsize=11)
    ax.set_title("Forest Plot: EM per configuration\n(bars = 95% CI)", fontsize=11)
    ax.grid(axis="x", alpha=0.3)
    ax.spines[["top","right"]].set_visible(False)

    # Baseline reference line
    baseline = "Always_Retrieve × Always_FAISS"
    bbase    = boot_map.get(baseline, {})
    if bbase:
        ax.axvline(x=bbase.get("em_mean",0), color="red", linestyle="--",
                   lw=1.2, alpha=0.5, label="Baseline")
        ax.legend(fontsize=9)

    # Panel 2: EM per bucket with 95% CI
    ax2    = axes[1]
    combos_sel = [c for c in combos if "BM25_Always" not in c]
    x      = np.arange(3)
    width  = 0.8 / max(len(combos_sel), 1)
    
    for i, combo in enumerate(combos_sel):
        b   = boot_map.get(combo, {})
        pre = combo.split(" × ")[0] if " × " in combo else combo
        color = COLORS.get(pre, "#666666")
        for j, bucket in enumerate(BUCKET_ORDER):
            em_b  = b.get(f"em_{bucket}")
            lo_b  = b.get(f"em_{bucket}_ci_lo")
            hi_b  = b.get(f"em_{bucket}_ci_hi")
            if em_b is None: continue
            pos = j + (i - len(combos_sel)/2) * width
            ax2.bar(pos, em_b, width*0.9, color=color, alpha=0.6,
                    edgecolor="white", linewidth=0.3)
            if lo_b is not None:
                ax2.errorbar(pos, em_b, yerr=[[em_b-lo_b],[hi_b-em_b]],
                             fmt="none", color="black", capsize=2, lw=1)

    ax2.set_xticks(np.arange(3))
    ax2.set_xticklabels([f"HIGH\n(s_pop≥1000)","MEDIUM\n(100-999)","LOW\n(<100)"],
                        fontsize=9)
    ax2.set_ylabel("EM", fontsize=11)
    ax2.set_title("EM per s_pop bucket ± 95% CI\n(without BM25_Always)", fontsize=11)
    ax2.grid(axis="y", alpha=0.3)
    ax2.spines[["top","right"]].set_visible(False)

    import matplotlib.patches as mpatches
    patches = [mpatches.Patch(color=c, label=n, alpha=0.7)
               for n, c in COLORS.items() if n != "BM25_Always"]
    ax2.legend(handles=patches, fontsize=8, loc="upper right")

    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"[PLOT] {output_path}")


def plot_mcnemar_heatmap(mcnemar_rows: List[Dict], output_path: str):
    """Heatmap of McNemar p-values."""
    if not MATPLOTLIB_AVAILABLE or not mcnemar_rows: return

    combos_b = sorted(set(r["system_b"] for r in mcnemar_rows))
    baseline  = mcnemar_rows[0]["system_a"] if mcnemar_rows else ""
    n = len(combos_b)
    if n == 0: return

    pvals   = np.ones((1, n))
    deltas  = np.zeros((1, n))

    for j, cb in enumerate(combos_b):
        for row in mcnemar_rows:
            if row["system_b"] == cb:
                pvals[0,j]  = row["pvalue"]
                deltas[0,j] = row["delta_em"]
                break

    fig, ax = plt.subplots(figsize=(max(8, n*1.5), 3))
    im = ax.imshow(pvals, cmap="RdYlGn_r", vmin=0, vmax=0.2, aspect="auto")

    for j in range(n):
        pv = pvals[0,j]; de = deltas[0,j]
        sig = "★" if pv < ALPHA else ""
        ax.text(j, 0, f"p={pv:.3f}\nΔ={de:+.3f}{sig}",
                ha="center", va="center", fontsize=8, fontweight="bold")

    ax.set_xticks(range(n))
    ax.set_xticklabels([c.replace(" × ","\n×") for c in combos_b],
                       fontsize=7.5, rotation=30, ha="right")
    ax.set_yticks([0])
    ax.set_yticklabels([f"vs\n{baseline[:30]}..."], fontsize=9)
    ax.set_title(f"McNemar Test p-values vs baseline\n"
                 f"(green=low p, ★=significant at α={ALPHA})", fontsize=11)

    plt.colorbar(im, ax=ax, label="p-value", shrink=0.8)
    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"[PLOT] {output_path}")


# ═════════════════════════════════════════════════════════════════════════════
# SECTION 6: TEXTUAL REPORT
# ═════════════════════════════════════════════════════════════════════════════

def write_statistical_report(mcnemar_rows: List[Dict],
                              bootstrap_rows: List[Dict],
                              path: str):
    lines = []
    lines.append("=" * 72)
    lines.append("FORMAL STATISTICAL TESTS — PopQA Ablation Study")
    lines.append("=" * 72)
    lines.append(f"CSV: {CSV_INPUT}")
    lines.append(f"α = {ALPHA}   Bootstrap: {N_BOOTSTRAP} resamples   Seed: {RANDOM_SEED}")
    lines.append("")

    lines.append("TEST 1 — McNemar (paired comparison vs baseline)")
    lines.append("─" * 72)
    lines.append(f"  {'System B':<42} | {'ΔEM':>6} | {'p-val':>8} | {'disc':>5} | {'Sig?':>5}")
    lines.append("  " + "─" * 68)
    n_sig = 0
    for row in sorted(mcnemar_rows, key=lambda x: x["pvalue"]):
        sig = "★ YES" if row["significant"] else "NO"
        if row["significant"]: n_sig += 1
        lines.append(
            f"  {row['system_b'][:42]:<42} | {row['delta_em']:>+6.4f} | "
            f"{row['pvalue']:>8.4f} | {row['n_discordant']:>5} | {sig:>5}"
        )
    lines.append(f"\n  Configurations significantly different from baseline: {n_sig}/{len(mcnemar_rows)}")
    lines.append("  ★ = p < 0.05 with Edwards continuity correction (or exact binomial test)")
    lines.append("")

    lines.append("TEST 2 — Bootstrap 95% CI (10,000 resamples)")
    lines.append("─" * 72)
    lines.append(f"  {'Combination':<42} | {'EM':>6} | {'CI95_lo':>8} | {'CI95_hi':>8} | {'Width':>6}")
    lines.append("  " + "─" * 72)
    for row in sorted(bootstrap_rows, key=lambda x: x["em_mean"], reverse=True):
        lines.append(
            f"  {row['combination'][:42]:<42} | {row['em_mean']:>6.4f} | "
            f"{row['em_ci95_lo']:>8.4f} | {row['em_ci95_hi']:>8.4f} | "
            f"{row['em_ci95_width']:>6.4f}"
        )
    lines.append("")

    lines.append("SCIENTIFIC INTERPRETATION")
    lines.append("─" * 72)
    lines.append(f"  Typical 95% CI width: ±{np.mean([r['em_ci95_width'] for r in bootstrap_rows])/2:.4f}")
    lines.append(f"  → EM differences < {np.mean([r['em_ci95_width'] for r in bootstrap_rows])/2:.4f}")
    lines.append(f"    are NOT statistically distinguishable.")
    lines.append("")
    lines.append("  The McNemar test is more sensitive because it leverages query pairing:")
    lines.append("  two systems with identical global EM can have different error patterns")
    lines.append("  (different queries), detectable by McNemar.")
    lines.append("")
    if n_sig > 0:
        lines.append(f"  ★ {n_sig} configuration(s) show(s) SIGNIFICANT difference")
        lines.append(f"    from baseline (McNemar p<{ALPHA}).")
    else:
        lines.append(f"  ○ No configuration shows significant difference")
        lines.append(f"    from baseline (McNemar p<{ALPHA}).")

    report = "\n".join(lines)
    with open(path, "w", encoding="utf-8") as f:
        f.write(report)
    print(f"[SAVE] Report: {path}")
    print("\n" + report)


# ═════════════════════════════════════════════════════════════════════════════
# SECTION 7: CSV SAVING
# ═════════════════════════════════════════════════════════════════════════════

def save_csv(rows: List[Dict], path: str, fieldnames: List[str]):
    if not rows: return
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)
    print(f"[SAVE] {path}")


# ═════════════════════════════════════════════════════════════════════════════
# SECTION 8: ENTRY POINT
# ═════════════════════════════════════════════════════════════════════════════

def main():
    print("=" * 70)
    print("  p4b_statistical_tests.py — McNemar + Bootstrap CI")
    print("=" * 70)

    if not os.path.isfile(CSV_INPUT):
        print(f"[ERROR] CSV not found: {CSV_INPUT}")
        print("  Run p3_router_popqa.py first.")
        sys.exit(1)

    results  = load_results(CSV_INPUT)
    combos   = sorted(results.keys())
    baseline = "Always_Retrieve × Always_FAISS"

    if baseline not in results:
        # Try alternatives in case of different naming
        for c in combos:
            if "Always_Retrieve" in c and "Always_FAISS" in c:
                baseline = c; break
        if baseline not in results:
            baseline = combos[0]
    print(f"[INFO] Baseline: '{baseline}'")

    # Test 1: McNemar
    mcnemar_rows = run_all_mcnemar(results, baseline)

    # Test 2: Bootstrap CI
    bootstrap_rows = run_bootstrap_for_all(results)

    # Test 3: Wilcoxon (best vs baseline, per bucket)
    best_combo = max(
        [c for c in combos if c != baseline],
        key=lambda c: np.mean([r["em"] for r in results[c].values()]),
        default=baseline
    )
    print(f"\n[WILCOXON] Best config: '{best_combo}'")
    wilcoxon_result = run_wilcoxon_bucket(results, baseline, best_combo)
    for b, wr in wilcoxon_result.items():
        sig = "★" if wr.get("significant") else "○"
        print(f"  {sig} bucket={b}: p={wr.get('pvalue','N/A')} n={wr.get('n',0)}")

    # Save CSVs
    save_csv(mcnemar_rows, os.path.join(STAT_DIR,"mcnemar_results.csv"),
             ["system_a","system_b","n_shared","em_a","em_b","delta_em",
              "statistic","pvalue","b","c","n_discordant","pct_discordant",
              "direction","significant","method","interpretation"])

    boot_cols = (["combination","n","em_mean","em_ci95_lo","em_ci95_hi","em_ci95_width",
                  "f1_mean","f1_ci95_lo","f1_ci95_hi"] +
                 [f"em_{b}" for b in BUCKET_ORDER] +
                 [f"em_{b}_ci_lo" for b in BUCKET_ORDER] +
                 [f"em_{b}_ci_hi" for b in BUCKET_ORDER])
    save_csv(bootstrap_rows, os.path.join(STAT_DIR,"bootstrap_ci.csv"), boot_cols)

    # Report
    write_statistical_report(mcnemar_rows, bootstrap_rows,
                              os.path.join(STAT_DIR, "statistical_report.txt"))

    # Plots
    if MATPLOTLIB_AVAILABLE:
        plot_em_distributions(results, bootstrap_rows,
                              os.path.join(STAT_DIR, "fig_em_distributions.png"))
        plot_mcnemar_heatmap(mcnemar_rows,
                             os.path.join(STAT_DIR, "fig_mcnemar_heatmap.png"))

    print(f"\n[DONE] Output in: {STAT_DIR}")


if __name__ == "__main__":
    main()